<?php
namespace KieServerClient\Protocol;

/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
final class AgendaFilterType {
    const RULE_NAME_EQUALS = 0;
    const RULE_NAME_MATCHES = 1;
    const RULE_NAME_STARTS_WITH = 2;
    const RULE_NAME_ENDS_WITH = 3;
    static public $__names = array(
        0 => 'RULE_NAME_EQUALS',
        1 => 'RULE_NAME_MATCHES',
        2 => 'RULE_NAME_STARTS_WITH',
        3 => 'RULE_NAME_ENDS_WITH',
    );
}
