<?php
namespace KieServerClient\Protocol;

use Thrift\Base\TBase;
use Thrift\Type\TType;

/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
class Authentication extends TBase {
    static $_TSPEC;

    /**
     * @var string
     */
    public $user = null;
    /**
     * @var string
     */
    public $password = null;
    /**
     * @var \KieServerClient\Protocol\Role
     */
    public $role = null;

    public function __construct($vals=null) {
        if (!isset(self::$_TSPEC)) {
            self::$_TSPEC = array(
                1 => array(
                    'var' => 'user',
                    'type' => TType::STRING,
                ),
                2 => array(
                    'var' => 'password',
                    'type' => TType::STRING,
                ),
                3 => array(
                    'var' => 'role',
                    'type' => TType::STRUCT,
                    'class' => '\KieServerClient\Protocol\Role',
                ),
            );
        }
        if (is_array($vals)) {
            parent::__construct(self::$_TSPEC, $vals);
        }
    }

    public function getName() {
        return 'Authentication';
    }

    public function read($input)
    {
        return $this->_read('Authentication', self::$_TSPEC, $input);
    }

    public function write($output) {
        return $this->_write('Authentication', self::$_TSPEC, $output);
    }

}
