<?php
namespace KieServerClient\Protocol;

use Thrift\Type\TConstant;


/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
final class Constant extends TConstant {
    static protected $PROTOCOL_VERSION;
    static protected $APPLICATION_XTHRIFT;
    static protected $ROLE_ARCHITECT;
    static protected $ROLE_ENGINEER;
    static protected $ROLE_MANAGER;
    static protected $ROLE_ANALYST;
    static protected $ROLE_OWNER;

    static protected function init_PROTOCOL_VERSION() {
        return "6.4.0.0";
    }

    static protected function init_APPLICATION_XTHRIFT() {
        return "application/x-thrift";
    }

    static protected function init_ROLE_ARCHITECT() {
        return "architect";
    }

    static protected function init_ROLE_ENGINEER() {
        return "engineer";
    }

    static protected function init_ROLE_MANAGER() {
        return "manager";
    }

    static protected function init_ROLE_ANALYST() {
        return "analyst";
    }

    static protected function init_ROLE_OWNER() {
        return "owner";
    }
}