<?php
namespace KieServerClient\Protocol;

use Thrift\Base\TBase;
use Thrift\Type\TType;

/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
class ExecutionResults extends TBase {
    static $_TSPEC;

    /**
     * @var string[]
     */
    public $outIdentifiers = null;
    /**
     * @var array
     */
    public $objects = null;

    public function __construct($vals=null) {
        if (!isset(self::$_TSPEC)) {
            self::$_TSPEC = array(
                1 => array(
                    'var' => 'outIdentifiers',
                    'type' => TType::LST,
                    'etype' => TType::STRING,
                    'elem' => array(
                        'type' => TType::STRING,
                    ),
                ),
                2 => array(
                    'var' => 'objects',
                    'type' => TType::MAP,
                    'ktype' => TType::STRING,
                    'vtype' => TType::STRING,
                    'key' => array(
                        'type' => TType::STRING,
                    ),
                    'val' => array(
                        'type' => TType::STRING,
                    ),
                ),
            );
        }
        if (is_array($vals)) {
            parent::__construct(self::$_TSPEC, $vals);
        }
    }

    public function getName() {
        return 'ExecutionResults';
    }

    public function read($input)
    {
        return $this->_read('ExecutionResults', self::$_TSPEC, $input);
    }

    public function write($output) {
        return $this->_write('ExecutionResults', self::$_TSPEC, $output);
    }

}
