<?php
namespace KieServerClient\Protocol;

use Thrift\Base\TBase;
use Thrift\Type\TType;

/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
class FireAllRulesCommand extends TBase {
    static $_TSPEC;

    /**
     * @var int
     */
    public $max = -1;
    /**
     * @var string
     */
    public $outIdentifier = null;
    /**
     * @var \KieServerClient\Protocol\AgendaFilter
     */
    public $agendaFilter = null;

    public function __construct($vals=null) {
        if (!isset(self::$_TSPEC)) {
            self::$_TSPEC = array(
                1 => array(
                    'var' => 'max',
                    'type' => TType::I32,
                ),
                2 => array(
                    'var' => 'outIdentifier',
                    'type' => TType::STRING,
                ),
                3 => array(
                    'var' => 'agendaFilter',
                    'type' => TType::STRUCT,
                    'class' => '\KieServerClient\Protocol\AgendaFilter',
                ),
            );
        }
        if (is_array($vals)) {
            parent::__construct(self::$_TSPEC, $vals);
        }
    }

    public function getName() {
        return 'FireAllRulesCommand';
    }

    public function read($input)
    {
        return $this->_read('FireAllRulesCommand', self::$_TSPEC, $input);
    }

    public function write($output) {
        return $this->_write('FireAllRulesCommand', self::$_TSPEC, $output);
    }

}
