<?php
namespace KieServerClient\Protocol;

use Thrift\Base\TBase;
use Thrift\Type\TType;

/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
class Info extends TBase {
    static $_TSPEC;

    /**
     * @var \KieServerClient\Protocol\ServerInfo
     */
    public $serverInfo = null;
    /**
     * @var \KieServerClient\Protocol\ListContainers
     */
    public $listContainers = null;
    /**
     * @var \KieServerClient\Protocol\ContainerInfo
     */
    public $ContainerInfo = null;

    public function __construct($vals=null) {
        if (!isset(self::$_TSPEC)) {
            self::$_TSPEC = array(
                1 => array(
                    'var' => 'serverInfo',
                    'type' => TType::STRUCT,
                    'class' => '\KieServerClient\Protocol\ServerInfo',
                ),
                2 => array(
                    'var' => 'listContainers',
                    'type' => TType::STRUCT,
                    'class' => '\KieServerClient\Protocol\ListContainers',
                ),
                3 => array(
                    'var' => 'ContainerInfo',
                    'type' => TType::STRUCT,
                    'class' => '\KieServerClient\Protocol\ContainerInfo',
                ),
            );
        }
        if (is_array($vals)) {
            parent::__construct(self::$_TSPEC, $vals);
        }
    }

    public function getName() {
        return 'Info';
    }

    public function read($input)
    {
        return $this->_read('Info', self::$_TSPEC, $input);
    }

    public function write($output) {
        return $this->_write('Info', self::$_TSPEC, $output);
    }

}
