<?php
namespace KieServerClient\Protocol;

use Thrift\Base\TBase;
use Thrift\Type\TType;

/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
class InsertObjectCommand extends TBase {
    static $_TSPEC;

    /**
     * @var string
     */
    public $object = null;
    /**
     * @var string
     */
    public $classCanonicalName = null;
    /**
     * @var bool
     */
    public $returnObject = true;
    /**
     * @var string
     */
    public $entryPoiny = "DEFAULT";
    /**
     * @var string
     */
    public $outIdentifier = null;

    public function __construct($vals=null) {
        if (!isset(self::$_TSPEC)) {
            self::$_TSPEC = array(
                1 => array(
                    'var' => 'object',
                    'type' => TType::STRING,
                ),
                2 => array(
                    'var' => 'classCanonicalName',
                    'type' => TType::STRING,
                ),
                3 => array(
                    'var' => 'returnObject',
                    'type' => TType::BOOL,
                ),
                4 => array(
                    'var' => 'entryPoiny',
                    'type' => TType::STRING,
                ),
                5 => array(
                    'var' => 'outIdentifier',
                    'type' => TType::STRING,
                ),
            );
        }
        if (is_array($vals)) {
            parent::__construct(self::$_TSPEC, $vals);
        }
    }

    public function getName() {
        return 'InsertObjectCommand';
    }

    public function read($input)
    {
        return $this->_read('InsertObjectCommand', self::$_TSPEC, $input);
    }

    public function write($output) {
        return $this->_write('InsertObjectCommand', self::$_TSPEC, $output);
    }

}
