<?php
namespace KieServerClient\Protocol;

/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
final class KieContainerStatus {
    const CREATING = 0;
    const STARTED = 1;
    const FAILED = 2;
    const DISPOSING = 3;
    const STOPPED = 4;
    static public $__names = array(
        0 => 'CREATING',
        1 => 'STARTED',
        2 => 'FAILED',
        3 => 'DISPOSING',
        4 => 'STOPPED',
    );
}