<?php

namespace KieServerClient\Protocol;

/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
final class KieScannerStatus {
    const UNKNOWN = 0;
    const CREATED = 1;
    const STARTED = 2;
    const SCANNING = 3;
    const STOPPED = 4;
    const DISPOSED = 5;
    static public $__names = array(
        0 => 'UNKNOWN',
        1 => 'CREATED',
        2 => 'STARTED',
        3 => 'SCANNING',
        4 => 'STOPPED',
        5 => 'DISPOSED',
    );
}