<?php
namespace KieServerClient\Protocol;

use Thrift\Type\TType;
use Thrift\Exception\TException;

/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
class KieServicesException extends TException {
    static $_TSPEC;

    /**
     * @var string
     */
    public $type = null;
    /**
     * @var string
     */
    public $message = null;
    /**
     * @var string
     */
    public $trace = null;

    public function __construct($vals=null) {
        if (!isset(self::$_TSPEC)) {
            self::$_TSPEC = array(
                1 => array(
                    'var' => 'type',
                    'type' => TType::STRING,
                ),
                2 => array(
                    'var' => 'message',
                    'type' => TType::STRING,
                ),
                3 => array(
                    'var' => 'trace',
                    'type' => TType::STRING,
                ),
            );
        }
        if (is_array($vals)) {
            parent::__construct(self::$_TSPEC, $vals);
        }
    }

    public function getName() {
        return 'KieServicesException';
    }

    public function read($input)
    {
        return $this->_read('KieServicesException', self::$_TSPEC, $input);
    }

    public function write($output) {
        return $this->_write('KieServicesException', self::$_TSPEC, $output);
    }

}
