<?php
namespace KieServerClient\Protocol;

use Thrift\Base\TBase;
use Thrift\Type\TType;

/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
class KieScannerInfo extends TBase {
    static $_TSPEC;

    /**
     * @var int
     */
    public $kieScannerStatus = null;
    /**
     * @var int
     */
    public $pollInterval = null;

    public function __construct($vals=null) {
        if (!isset(self::$_TSPEC)) {
            self::$_TSPEC = array(
                1 => array(
                    'var' => 'kieScannerStatus',
                    'type' => TType::I32,
                ),
                2 => array(
                    'var' => 'pollInterval',
                    'type' => TType::I64,
                ),
            );
        }
        if (is_array($vals)) {
            parent::__construct(self::$_TSPEC, $vals);
        }
    }

    public function getName() {
        return 'KieScannerInfo';
    }

    public function read($input)
    {
        return $this->_read('KieScannerInfo', self::$_TSPEC, $input);
    }

    public function write($output) {
        return $this->_write('KieScannerInfo', self::$_TSPEC, $output);
    }

}
