<?php
namespace KieServerClient\Protocol;

use Thrift\Base\TBase;
use Thrift\Type\TType;

/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
class KieServicesClient extends TBase {
    static $_TSPEC;

    /**
     * @var string
     */
    public $client = null;
    /**
     * @var \KieServerClient\Protocol\Version
     */
    public $version = null;
    /**
     * @var \KieServerClient\Protocol\Authentication
     */
    public $authentication = null;

    public function __construct($vals=null) {
        if (!isset(self::$_TSPEC)) {
            self::$_TSPEC = array(
                1 => array(
                    'var' => 'client',
                    'type' => TType::STRING,
                ),
                2 => array(
                    'var' => 'version',
                    'type' => TType::STRUCT,
                    'class' => '\KieServerClient\Protocol\Version',
                ),
                3 => array(
                    'var' => 'authentication',
                    'type' => TType::STRUCT,
                    'class' => '\KieServerClient\Protocol\Authentication',
                ),
            );
        }
        if (is_array($vals)) {
            parent::__construct(self::$_TSPEC, $vals);
        }
    }

    public function getName() {
        return 'KieServicesClient';
    }

    public function read($input)
    {
        return $this->_read('KieServicesClient', self::$_TSPEC, $input);
    }

    public function write($output) {
        return $this->_write('KieServicesClient', self::$_TSPEC, $output);
    }

}
