<?php
namespace KieServerClient\Protocol;

use Thrift\Base\TBase;
use Thrift\Type\TType;

/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
class KieServicesResponse extends TBase {
    static $_TSPEC;

    /**
     * @var string
     */
    public $protocolVersion = "6.4.0.0";
    /**
     * @var \KieServerClient\Protocol\Response
     */
    public $response = null;

    public function __construct($vals=null) {
        if (!isset(self::$_TSPEC)) {
            self::$_TSPEC = array(
                1 => array(
                    'var' => 'protocolVersion',
                    'type' => TType::STRING,
                ),
                2 => array(
                    'var' => 'response',
                    'type' => TType::STRUCT,
                    'class' => '\KieServerClient\Protocol\Response',
                ),
            );
        }
        if (is_array($vals)) {
            parent::__construct(self::$_TSPEC, $vals);
        }
    }

    public function getName() {
        return 'KieServicesResponse';
    }

    public function read($input)
    {
        return $this->_read('KieServicesResponse', self::$_TSPEC, $input);
    }

    public function write($output) {
        return $this->_write('KieServicesResponse', self::$_TSPEC, $output);
    }

}

