<?php
namespace KieServerClient\Protocol;

use Thrift\Base\TBase;
use Thrift\Type\TType;

/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
class ReleaseId extends TBase {
    static $_TSPEC;

    /**
     * @var string
     */
    public $groupId = null;
    /**
     * @var string
     */
    public $artifactId = null;
    /**
     * @var string
     */
    public $version = null;

    public function __construct($vals=null) {
        if (!isset(self::$_TSPEC)) {
            self::$_TSPEC = array(
                1 => array(
                    'var' => 'groupId',
                    'type' => TType::STRING,
                ),
                2 => array(
                    'var' => 'artifactId',
                    'type' => TType::STRING,
                ),
                3 => array(
                    'var' => 'version',
                    'type' => TType::STRING,
                ),
            );
        }
        if (is_array($vals)) {
            parent::__construct(self::$_TSPEC, $vals);
        }
    }

    public function getName() {
        return 'ReleaseId';
    }

    public function read($input)
    {
        return $this->_read('ReleaseId', self::$_TSPEC, $input);
    }

    public function write($output) {
        return $this->_write('ReleaseId', self::$_TSPEC, $output);
    }

}

