<?php
namespace KieServerClient\Protocol;

use Thrift\Base\TBase;
use Thrift\Type\TType;

/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
class Response extends TBase {
    static $_TSPEC;

    /**
     * @var \KieServerClient\Protocol\Info
     */
    public $info = null;
    /**
     * @var \KieServerClient\Protocol\Results
     */
    public $results = null;
    /**
     * @var \KieServerClient\Protocol\KieServicesException
     */
    public $kieServicesException = null;

    public function __construct($vals=null) {
        if (!isset(self::$_TSPEC)) {
            self::$_TSPEC = array(
                1 => array(
                    'var' => 'info',
                    'type' => TType::STRUCT,
                    'class' => '\KieServerClient\Protocol\Info',
                ),
                2 => array(
                    'var' => 'results',
                    'type' => TType::STRUCT,
                    'class' => '\KieServerClient\Protocol\Results',
                ),
                3 => array(
                    'var' => 'kieServicesException',
                    'type' => TType::STRUCT,
                    'class' => '\KieServerClient\Protocol\KieServicesException',
                ),
            );
        }
        if (is_array($vals)) {
            parent::__construct(self::$_TSPEC, $vals);
        }
    }

    public function getName() {
        return 'Response';
    }

    public function read($input)
    {
        return $this->_read('Response', self::$_TSPEC, $input);
    }

    public function write($output) {
        return $this->_write('Response', self::$_TSPEC, $output);
    }

}
