<?php
namespace KieServerClient\Protocol;

use Thrift\Base\TBase;
use Thrift\Type\TType;

/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
class ServerInfo extends TBase {
    static $_TSPEC;

    /**
     * @var \KieServerClient\Protocol\Version
     */
    public $version = null;
    /**
     * @var string
     */
    public $serverId = null;
    /**
     * @var string
     */
    public $serverName = null;
    /**
     * @var string
     */
    public $kieServerLocation = null;
    /**
     * @var string[]
     */
    public $serverExtensions = null;

    public function __construct($vals=null) {
        if (!isset(self::$_TSPEC)) {
            self::$_TSPEC = array(
                1 => array(
                    'var' => 'version',
                    'type' => TType::STRUCT,
                    'class' => '\KieServerClient\Protocol\Version',
                ),
                2 => array(
                    'var' => 'serverId',
                    'type' => TType::STRING,
                ),
                3 => array(
                    'var' => 'serverName',
                    'type' => TType::STRING,
                ),
                4 => array(
                    'var' => 'kieServerLocation',
                    'type' => TType::STRING,
                ),
                5 => array(
                    'var' => 'serverExtensions',
                    'type' => TType::LST,
                    'etype' => TType::STRING,
                    'elem' => array(
                        'type' => TType::STRING,
                    ),
                ),
            );
        }
        if (is_array($vals)) {
            parent::__construct(self::$_TSPEC, $vals);
        }
    }

    public function getName() {
        return 'ServerInfo';
    }

    public function read($input)
    {
        return $this->_read('ServerInfo', self::$_TSPEC, $input);
    }

    public function write($output) {
        return $this->_write('ServerInfo', self::$_TSPEC, $output);
    }

}
